---
apiVersion: v1
kind: Service
metadata:
  name: my-ext-hello
  labels:
    app: my-ext-hello
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: my-ext-hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ext-hello
  labels:
    app: my-ext-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ext-hello
  template:
    metadata:
      labels:
        app: my-ext-hello
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/my-ext-hello/my-ext-hello
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: my-ext-hello
spec:
  to:
    kind: Service
    name: my-ext-hello
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
